### PR TITLE
Support for NextSeq (NB) and NovaSeq 6000

### PR DESCRIPTION
**Pull request by davmlaw**
Support my NextSeq with code "NB", also support NovaSeq 6000

In both of these, RunParameters.xml has an upper case R.

### CODE REVIEW

**Comment by nthmost** [comment]
Hi @davmlaw !  I apologize I never saw this pull request until now.  

(Long story, lots of life changes, now back in action on taking up serious open source maintenance again.)

What I need to be able to merge this pull request is *sample data*.  Just the basic quality metrics are sufficient, no need to include actual run data.

I realized this pull request is almost 2 years old, so I'm not holding my breath -- but I really do want to make illuminate the best it can be.  Here's hoping 🤞

**Comment by davmlaw** [comment]
Hi @nthmost - I have added some Novaseq data from one of our runs. I copied what I had that matched previous sample data for other machines, but please explicitly list what you want if you need anything

**Comment by davmlaw** [comment]
@nthmost - any other files you wanted?

**Comment by nthmost** [comment]
@davmlaw Oh great, thanks!  (Just back from backpacking off-grid).  Will work on this ASAP.

**Pull request merged**
